<?php


namespace app\admin\controller;


use app\admin\library\BaseController;
use app\admin\model\AdminUserModel;

class AdminUser extends BaseController
{
    public $searchFields = ['id'];
    public $AdminUserModel = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->AdminUserModel = new AdminUserModel();
    }

    //获取列表
    public function getData()
    {
        try{
            $condition = $this->getPageRows();
            $condition['where'] = $this->filterSearchFields($this->searchFields);
            $condition['order'] = ['id'=>'desc'];
            $data['lists'] =  $this->AdminUserModel->withSearch(['diySelect'],$condition)->select();
            $data['total'] =  $this->AdminUserModel->withSearch(['diyCount'],$condition)->count();
            $this->assembleTableData('200', 'success', $data);
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->AdminUserModel->where('id',$post)->find();
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

    // 修改
    public function  edit()
    {
        $mustFields = ['id','user_name','status'];
        $extFields = ['sign','head_img'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $rec = AdminUserModel::get(['id' => $param['id']]);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }

        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();

    }

    //添加
    public function add()
    {
        $mustFields = ['user_name','status'];
        $extFields = ['sign','head_img','password'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $param['create_time'] = date('Y-m-d H:i:s');
            $param['password'] = md5(md5($param['password']));
            if ($this->AdminUserModel->save($param)) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //删除
    public  function delete()
    {
        try {
            $post = $this->request->post('id');
            $this->AdminUserModel->destroy($post);
            $this->ret['code'] = 200;
            $this->ret['msg'] = 'success';
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //修改密码
    public function editPwd() {
        $post = $this->request->param();
        $rec = AdminUserModel::get(['id' => $post['id']]);
        $rec->password = md5(md5($post['password']));
        if ($rec->save()) {
            $this->ret['code'] = 200;
            $this->ret['msg'] = '编辑成功';
        } else {
            $this->ret['code'] = 500;
            $this->ret['msg'] = '编辑失败';
        }
        $this->outPutJson();
    }

}