<?php

namespace app\admin\controller;

use app\admin\library\BaseController;
use app\admin\model\NewsStudentModel;

class NewsStudent extends BaseController
{
    public $searchFields = [];
    public $NewsStudentModel = [];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->NewsStudentModel =  new NewsStudentModel()  ;
    }

    public function getData()
    {
        try{
            $condition = $this->getPageRows();
            $condition['where'] = $this->filterSearchFields($this->searchFields);
            $condition['order'] = ['id'=>'desc'];
            $data['lists'] =  $this->NewsStudentModel->withSearch(['diySelect'],$condition)->select()->toArray();
            $data['total'] =  $this->NewsStudentModel->withSearch(['diyCount'],$condition)->count();
            $this->assembleTableData(200, 'success', $data);
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->NewsStudentModel->where('id',$post)->find();
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

    // 修改
    public function  edit()
    {
        $mustFields = ['id','title','user_name','score','school_name','college','thumb','brief','content','status'];
        $extFields = ['click_num'];
        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $rec = NewsStudentModel::get(['id' => $param['id']]);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //添加
    public function add()
    {
        $mustFields = ['title','user_name','score','school_name','college','thumb','brief','content','status'];
        $extFields = ['click_num'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $param['create_time'] = date('Y-m-d H:i:s');
            if ($this->NewsStudentModel->save($param)) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //删除
    public  function delete()
    {
        try {
            $post = $this->request->post('id');
            $this->NewsStudentModel->destroy($post);
            $this->ret['code'] = 200;
            $this->ret['msg'] = 'success';
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }
}