<?php

namespace app\admin\controller;
use app\admin\library\BaseController;
use app\admin\model\SchoolModel;

class School extends BaseController
{
    public $searchFields = ['city_id','name','school_type_id'];
    public $SchoolModel = [];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->SchoolModel =  new SchoolModel()  ;
    }

    public function getData()
    {
        try{
            $condition = $this->getPageRows();
            $condition['where'] = $this->filterSearchFields($this->searchFields);
            $condition['order'] = ['id'=>'desc'];
            $data['lists'] =  $this->SchoolModel->withSearch(['diySelect'],$condition)->select();
            foreach ($data['lists'] as $k => &$v) {
                $v['school_tip_id']  = explode(',',$v['school_tip_id']);
            }
            $data['total'] =  $this->SchoolModel->withSearch(['diyCount'],$condition)->count();
            $this->assembleTableData(200, 'success', $data);
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->SchoolModel->where('id',$post)->find();
        if($data['school_tip_id']){
            $res   = explode(',',$data['school_tip_id']);
            foreach ($res  as $k =>&$v) {
                if($v == '' || $v == 0){
                    continue;
                }
                $school_tip_id[] = intval($v);
            }
            $data['school_tip_id']  = $school_tip_id;

        }else{
            $data['school_tip_id'] = [];
        }
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

    // 修改
    public function  edit()
    {
        $mustFields = ['id','name','school_id','degree','city_id','nature','school_type_id','school_belong'];
        $extFields = ['school_hot','logo','found_time','school_url','school_admissions_url','school_panoramic','status','desc','school_tip_id','school_img','has_master','has_doctor'];
        try {
            $param = $this->receiveParam($mustFields, $extFields);
            if($param['school_tip_id'] != ''){
                $param['school_tip_id'] = implode(',',$param['school_tip_id']);
            }
            $rec = SchoolModel::get(['id' => $param['id']]);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }

        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //添加
    public function add()
    {
        $mustFields = ['name','school_id','degree','city_id','nature','school_type_id','school_belong'];
        $extFields = ['school_hot','logo','school_admissions_url','found_time','school_url','school_panoramic','status','desc','school_tip_id','school_img','has_master','has_doctor'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            if ($this->SchoolModel->save($param)) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //删除
    public  function delete()
    {
        try {
            $post = $this->request->post('id');
            $this->SchoolModel->destroy($post);
            $this->ret['code'] = 200;
            $this->ret['msg'] = 'success';
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }
    
   public  function cityDelete()
    {
        try {
            $city_id = $this->request->param('city_id');
        	$this->SchoolModel->where('city_id',$city_id)->delete();
            $this->ret['code'] = 200;
            $this->ret['msg'] = 'success';
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }
    
}