<?php

namespace app\admin\controller;

use app\admin\library\BaseController;
use app\admin\model\SpecialtyModel;

class Specialty extends BaseController
{
    public $searchFields = ['id','name'];
    public $SpecialtyModel = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->SpecialtyModel = new SpecialtyModel();
    }

    //获取列表
    public function getData()
    {
        try {
            $condition = $this->getPageRows();
            $condition['where'] = $this->filterSearchFields($this->searchFields);
            $condition['order'] = ['id'=>'desc'];
            $data['lists'] =  $this->SpecialtyModel->withSearch(['diySelect'],$condition)->select();
            $data['total'] =  $this->SpecialtyModel->withSearch(['diyCount'],$condition)->count();
            $this->assembleTableData('200', 'success', $data);
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->SpecialtyModel->where('id',$post)->find()->toArray();
        if($data['parent_id'] == 0){
            $data['first_pid'] = 0;
            $data['second_pid'] = 0;
        }else{
            $res = $this->SpecialtyModel->where('specialty_code',$data['parent_id'])->find();
            if($res['parent_id'] == 0) {
                $data['first_pid'] = $res['id'];
                $data['second_pid'] = 0;
            }else{
                $res_t = $this->SpecialtyModel->where('specialty_code',$res['parent_id'])->find();
                $data['first_pid'] =   $res_t['id'];
                $data['first_code'] =   $res_t['specialty_code'];
                $data['second_pid'] =  $res['id'];
            }
        }
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

    // 修改
    public function  edit()
    {
        $mustFields = ['id','status','name'];
        $extFields = ['specialty_code','degree','parent_id','desc','study_year'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $rec = SpecialtyModel::get(['id' => $param['id']]);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //添加
    public function add()
    {
        $mustFields = ['status','name'];
        $extFields = ['specialty_code','degree','parent_id','desc','study_year'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            if ($this->SpecialtyModel->save($param)) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //删除
    public  function delete()
    {
        try {
            $post = $this->request->post('id');
            $this->SpecialtyModel->destroy($post);
            $this->ret['code'] = 200;
            $this->ret['msg'] = 'success';
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    public function getChild()
    {
        $parent_id =    $this->request->param('parent_id');
        $parent_id =    $parent_id == '' ? 0:$parent_id;
        $data =     $this->SpecialtyModel->where('parent_id',$parent_id)->select();
        $this->ret['code'] = 200;
        $this->ret['data'] = $data;
        $this->outPutJson();
    }
}