<?php

namespace app\admin\controller;

use app\admin\library\BaseController;
use app\admin\model\SpecialtyOverviewModel;

class SpecialtyOverview extends BaseController
{
    public $searchFields = ['id'];
    public $SpecialtyOverviewModel = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->SpecialtyOverviewModel = new SpecialtyOverviewModel();
    }

    // 修改
    public function  edit()
    {
        $mustFields = ['id','specialty_id','qualification'];
        $extFields = ['wenli_proportion','nannv_proportion','introduction','train_objective','train_requirements','discipline_required','knowledge_capability','pg_direction','main_course','employment_direction','social_celebrities'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $param['knowledge_capability'] = $param['knowledge_capability'] == '' ? $param['knowledge_capability']:json_encode($param['knowledge_capability']);
            $rec = SpecialtyOverviewModel::get(['id' => $param['id']]);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //获取详情
    public function getDataDesc() {
        try{
            $specialty_id = $this->request->param('id');
            $data =   $this->SpecialtyOverviewModel->where('specialty_id',$specialty_id)->find();
            if($data){
                $this->ret['code'] = 200;
                $this->ret['data'] = $data;
            }else{
                $this->SpecialtyOverviewModel->specialty_id = $specialty_id;
                $this->SpecialtyOverviewModel->save();
                $this->SpecialtyOverviewModel->id;
                $this->ret['code'] = 201;
                $this->ret['data'] = $this->SpecialtyOverviewModel->id;
            }
        }catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }
}